import { fill, lesson, mcq, order, output, typeIn, unit } from "./helpers";

export const javascript = {
  id: "javascript",
  title: "JavaScript",
  tagline: "The language of the web, one drill at a time.",
  icon: "🟨",
  accent: "#f5d90a",
  units: [
    unit("js-boot", "Boot sequence", "Values, types, and the comparisons that trip interviews.", [
      lesson("js-1", "Values & types", [
        mcq(
          "js-1-a",
          "Which of these is a string?",
          ['"42"', "42", "true", "null"],
          '"42"',
          "Quotes make a string — even when the characters look like a number.",
        ),
        output(
          "js-1-b",
          "What does this log?",
          "console.log(typeof 3.14);",
          ["number", "float", "decimal", "NaN"],
          "number",
          "JavaScript has one numeric type. Integers and floats are both `number`.",
          { language: "javascript" },
        ),
        fill(
          "js-1-c",
          "Complete the boolean.",
          "const ready = ___;",
          ["true", '"true"', "1", "True"],
          "true",
          "`true` and `false` are boolean literals. Strings and numbers are different types.",
          { language: "javascript" },
        ),
        mcq(
          "js-1-d",
          "What does `typeof null` return?",
          ["object", "null", "undefined", "boolean"],
          "object",
          "A famous language quirk: `typeof null` is `\"object\"`. Check with `=== null`.",
        ),
        typeIn(
          "js-1-e",
          "A declared variable with no value is… (one word)",
          "undefined",
          "`undefined` means “not assigned yet”. `null` is an intentional empty value.",
        ),
      ]),
      lesson("js-2", "Equality", [
        mcq(
          "js-2-a",
          "Which operator compares value and type?",
          ["===", "==", "=", "!=="],
          "===",
          "`===` is strict equality. `==` coerces types first and surprises people.",
        ),
        output(
          "js-2-b",
          "What does this log?",
          "console.log(0 == false);",
          ["true", "false", "0", "TypeError"],
          "true",
          "`==` coerces `false` to `0`, so this is `true`. Prefer `===`.",
          { language: "javascript" },
        ),
        output(
          "js-2-c",
          "What does this log?",
          "console.log(0 === false);",
          ["false", "true", "0", "undefined"],
          "false",
          "A number is not a boolean. Strict equality keeps you honest.",
          { language: "javascript" },
        ),
        fill(
          "js-2-d",
          "Make this comparison true.",
          'Number("8") === ___;',
          ["8", '"8"', "true", "NaN"],
          "8",
          "`Number(\"8\")` converts the string to the number `8`.",
          { language: "javascript" },
        ),
        mcq(
          "js-2-e",
          "How should you test for NaN?",
          ["Number.isNaN(value)", "value === NaN", "value == NaN", "typeof value === \"NaN\""],
          "Number.isNaN(value)",
          "`NaN === NaN` is `false`. Use `Number.isNaN`.",
        ),
      ]),
    ]),
    unit("js-memory", "Memory", "How you name values — and why `const` is the default.", [
      lesson("js-3", "let & const", [
        mcq(
          "js-3-a",
          "Which binding cannot be reassigned?",
          ["const", "let", "var", "both let and var"],
          "const",
          "`const` prevents reassignment. The value itself can still mutate if it's an object.",
        ),
        fill(
          "js-3-b",
          "Declare a block-scoped counter.",
          "___ count = 0;",
          ["let", "var", "static", "def"],
          "let",
          "`let` is block-scoped and reassignable. That's what you want for a counter.",
          { language: "javascript" },
        ),
        output(
          "js-3-c",
          "What happens?",
          "const n = 1;\nn = 2;",
          ["TypeError", "n becomes 2", "undefined", "NaN"],
          "TypeError",
          "Reassigning a `const` throws in strict mode (modules are always strict).",
          { language: "javascript" },
        ),
        mcq(
          "js-3-d",
          "Which keyword is function-scoped and hoisted with `undefined`?",
          ["var", "let", "const", "using"],
          "var",
          "`var` is the old tool. Prefer `let`/`const` to avoid hoisting surprises.",
        ),
        order(
          "js-3-e",
          "Build a tiny script that logs 2.",
          ["let n = 1;", "n += 1;", "console.log(n);"],
          "Declare, mutate, then read. Order matters because `let` is not hoisted like `var`.",
        ),
      ]),
      lesson("js-4", "Strings", [
        fill(
          "js-4-a",
          "Interpolate the name.",
          "const msg = `Hi, ${___}`;",
          ["name", "\"name\"", "{name}", "$name"],
          "name",
          "Template literals use `${expression}` inside backticks.",
          { language: "javascript" },
        ),
        output(
          "js-4-b",
          "What does this log?",
          'console.log("code".length);',
          ["4", "3", '"code"', "undefined"],
          "4",
          "`.length` counts UTF-16 code units. For `\"code\"` that's 4.",
          { language: "javascript" },
        ),
        mcq(
          "js-4-c",
          "Which method returns a new string and never mutates the original?",
          ["trim()", "push()", "splice()", "sort()"],
          "trim()",
          "Strings are immutable. Methods like `trim`, `slice`, and `toUpperCase` return new strings.",
        ),
        fill(
          "js-4-d",
          "Pick the nullish operator — it only falls through for null/undefined.",
          "const label = title ___ \"Untitled\";",
          ["??", "||", "&&", "?:"],
          "??",
          "`||` also skips empty strings and `0`. `??` only skips `null` and `undefined`.",
          { language: "javascript" },
        ),
        typeIn(
          "js-4-e",
          "The character used for template literals (one word: backtick / quote / hash)",
          "backtick",
          "Backticks (`` ` ``) enable interpolation and multi-line strings.",
        ),
      ]),
    ]),
    unit("js-data", "Data moves", "Arrays, objects, and the functions that transform them.", [
      lesson("js-5", "Arrays", [
        output(
          "js-5-a",
          "What does this log?",
          "console.log([10, 20, 30].length);",
          ["3", "2", "30", "undefined"],
          "3",
          "`.length` is the count of elements, not the last value.",
          { language: "javascript" },
        ),
        fill(
          "js-5-b",
          "Keep only even numbers.",
          "nums.filter((n) => n % 2 === ___);",
          ["0", "1", "2", "n"],
          "0",
          "Even numbers have remainder `0` when divided by 2.",
          { language: "javascript" },
        ),
        mcq(
          "js-5-c",
          "Which method transforms every item and returns a new array?",
          ["map", "forEach", "push", "find"],
          "map",
          "`map` returns a new array. `forEach` is for side effects and returns `undefined`.",
        ),
        fill(
          "js-5-d",
          "Pull the first two values.",
          "const [first, ___] = scores;",
          ["second", "...rest", "0", "scores[1]"],
          "second",
          "Array destructuring names positions from the left.",
          { language: "javascript" },
        ),
        order(
          "js-5-e",
          "Build an array of doubled values.",
          ["const nums = [1, 2, 3];", "const doubled = nums.map((n) => n * 2);", "console.log(doubled);"],
          "`map` keeps the original array intact and returns a new one — a core JS habit.",
        ),
      ]),
      lesson("js-6", "Functions", [
        fill(
          "js-6-a",
          "Return the square.",
          "const sq = (n) => ___;",
          ["n * n", "n + n", "n++", "return n"],
          "n * n",
          "Arrow functions with an expression body return that expression automatically.",
          { language: "javascript" },
        ),
        mcq(
          "js-6-b",
          "What does a function return if it has no `return`?",
          ["undefined", "null", "0", "false"],
          "undefined",
          "Missing `return` is a common bug in callbacks and reducers.",
        ),
        fill(
          "js-6-c",
          "Give the parameter a default.",
          "function greet(name = ___) {",
          ['"friend"', "null", "name", "arguments[0]"],
          '"friend"',
          "Default parameters run when the argument is `undefined`.",
          { language: "javascript" },
        ),
        output(
          "js-6-d",
          "What does this log?",
          "const add = (a, b = 1) => a + b;\nconsole.log(add(4));",
          ["5", "4", "NaN", "undefined"],
          "5",
          "`b` falls back to `1`, so `4 + 1` is `5`.",
          { language: "javascript" },
        ),
        typeIn(
          "js-6-e",
          "The keyword that sends a value out of a function:",
          "return",
          "`return` exits the function immediately with a value (or `undefined`).",
        ),
      ]),
    ]),
  ],
};
