import { fill, lesson, mcq, order, output, typeIn, unit } from "./helpers";

export const python = {
  id: "python",
  title: "Python",
  tagline: "Readable syntax, serious data chops.",
  icon: "🐍",
  accent: "#3776ab",
  units: [
    unit("py-core", "Core syntax", "How Python names things and talks back.", [
      lesson("py-1", "Basics", [
        fill(
          "py-1-a",
          "Print a greeting.",
          "___(\"hello\")",
          ["print", "echo", "console.log", "printf"],
          "print",
          "`print` writes to stdout. No parentheses in Python 2 — you're on Python 3.",
          { language: "python" },
        ),
        mcq(
          "py-1-b",
          "Which prefix starts a comment?",
          ["#", "//", "--", "/*"],
          "#",
          "Python comments start with `#` and run to the end of the line.",
        ),
        output(
          "py-1-c",
          "What does this print?",
          "print(type(3) is int)",
          ["True", "False", "int", "None"],
          "True",
          "`3` is an `int`. `type(3) is int` is a strict identity check on the type object.",
          { language: "python" },
        ),
        fill(
          "py-1-d",
          "F-string interpolation.",
          'name = "Ali"\nprint(f"hi {___}")',
          ["name", '"name"', "$name", "name()"],
          "name",
          "F-strings evaluate expressions inside `{}`.",
          { language: "python" },
        ),
      ]),
      lesson("py-2", "Collections", [
        output(
          "py-2-a",
          "What does this print?",
          "print(len([\"a\", \"b\", \"c\"]))",
          ["3", "2", "1", "None"],
          "3",
          "`len` works on lists, dicts, strings, and most collections.",
          { language: "python" },
        ),
        fill(
          "py-2-b",
          "Read a dict value.",
          'user = {"role": "dev"}\nrole = user[___]',
          ['"role"', "role", "0", ".role"],
          '"role"',
          "Dict keys are looked up with brackets. Missing keys raise `KeyError`.",
          { language: "python" },
        ),
        mcq(
          "py-2-c",
          "Which structure is ordered, unique, and hash-based?",
          ["set", "list", "tuple", "string"],
          "set",
          "Sets drop duplicates. Lists keep order and repeats. Tuples are immutable sequences.",
        ),
        order(
          "py-2-d",
          "Build a list of squares with a comprehension.",
          ["nums = [1, 2, 3]", "squares = [n * n for n in nums]", "print(squares)"],
          "Comprehensions are the Pythonic `map` — compact and readable when they stay short.",
        ),
      ]),
    ]),
    unit("py-flow", "Flow", "Functions, branches, and the None that hides bugs.", [
      lesson("py-3", "Control", [
        fill(
          "py-3-a",
          "Complete the branch.",
          "if n > 0:\n    print(\"pos\")\n___:\n    print(\"other\")",
          ["else", "elif", "finally", "except"],
          "else",
          "`else` runs when the `if` (and any `elif`) did not.",
          { language: "python" },
        ),
        mcq(
          "py-3-b",
          "Which values are falsy?",
          ["0, \"\", [], None", "only None", "only False", "negative numbers"],
          "0, \"\", [], None",
          "Empty collections, `0`, `\"\"`, and `None` are all falsy in boolean context.",
        ),
        fill(
          "py-3-c",
          "Loop over items.",
          "for item ___ xs:",
          ["in", "of", "inside", "from"],
          "in",
          "`for x in iterable` is Python's only for-loop shape.",
          { language: "python" },
        ),
        output(
          "py-3-d",
          "What does this print?",
          "print(\"hi\" if True else \"bye\")",
          ["hi", "bye", "True", "None"],
          "hi",
          "That's a ternary expression: `a if cond else b`.",
          { language: "python" },
        ),
      ]),
      lesson("py-4", "Functions", [
        fill(
          "py-4-a",
          "Define a function.",
          "___ add(a, b):",
          ["def", "function", "fn", "lambda"],
          "def",
          "`def` creates a named function. `lambda` is for tiny anonymous ones.",
          { language: "python" },
        ),
        mcq(
          "py-4-b",
          "What does a function return if it has no `return`?",
          ["None", "undefined", "0", "False"],
          "None",
          "Python's empty return is `None`, not `undefined`.",
        ),
        fill(
          "py-4-c",
          "Default argument.",
          "def greet(name=___):",
          ['"friend"', "None", "name", "self"],
          '"friend"',
          "Default args are evaluated once, at function definition — never pass a mutable list as a default.",
          { language: "python" },
        ),
        typeIn(
          "py-4-d",
          "The object that means “no value” in Python:",
          "None",
          "`None` is a singleton. Check with `is None`, not `== None`.",
        ),
      ]),
    ]),
  ],
};
