import { fill, lesson, mcq, order, output, typeIn, unit } from "./helpers";

export const typescript = {
  id: "typescript",
  title: "TypeScript",
  tagline: "Catch bugs before they ship.",
  icon: "🔷",
  accent: "#3178c6",
  units: [
    unit("ts-types", "Type layer", "Annotations, objects, and the compiler's ground rules.", [
      lesson("ts-1", "Annotations", [
        fill(
          "ts-1-a",
          "Annotate this count.",
          "let count: ___ = 0;",
          ["number", "Number", "int", "any"],
          "number",
          "Primitive types are lowercase: `number`, `string`, `boolean`.",
          { language: "typescript" },
        ),
        mcq(
          "ts-1-b",
          "Which type should you almost never reach for?",
          ["any", "string", "unknown", "never"],
          "any",
          "`any` turns the compiler off. Prefer `unknown` and narrow it.",
        ),
        fill(
          "ts-1-c",
          "This function returns nothing visible.",
          "function log(msg: string): ___ {",
          ["void", "null", "undefined", "never"],
          "void",
          "`void` means the return value isn't meant to be used.",
          { language: "typescript" },
        ),
        output(
          "ts-1-d",
          "Does this compile?",
          'const id: number = "42";',
          ["No — string is not number", "Yes", "Only in JavaScript", "Yes, it coerces"],
          "No — string is not number",
          "TypeScript will not silently coerce a string into a number annotation.",
          { language: "typescript" },
        ),
      ]),
      lesson("ts-2", "Objects", [
        fill(
          "ts-2-a",
          "Mark email as optional.",
          "type User = { email___: string };",
          ["?", "!", "| null", "*"],
          "?",
          "`email?: string` means the property can be omitted.",
          { language: "typescript" },
        ),
        mcq(
          "ts-2-b",
          "What does `readonly` on a property do?",
          ["Blocks reassignment of that field", "Freezes the runtime object", "Makes it private", "Removes it from JSON"],
          "Blocks reassignment of that field",
          "`readonly` is a compile-time constraint. Runtime mutability is unchanged.",
        ),
        order(
          "ts-2-c",
          "Define a User type and a value that satisfies it.",
          [
            "type User = { name: string };",
            'const ali: User = { name: "Ali" };',
            "console.log(ali.name);",
          ],
          "Types are erased at compile time — they document the shape, then disappear.",
        ),
        typeIn(
          "ts-2-d",
          "Keyword to declare a named object shape (interface / class / enum):",
          "interface",
          "`interface` and `type` both model objects. Interviews often expect `interface` for shapes.",
        ),
      ]),
    ]),
    unit("ts-narrow", "Narrow & reuse", "Unions, narrowing, and generics — the real TypeScript muscle.", [
      lesson("ts-3", "Unions", [
        fill(
          "ts-3-a",
          "Allow two string literals.",
          'type Mode = "light" | ___;',
          ['"dark"', "dark", "string", "null"],
          '"dark"',
          "String literal unions are how you model finite modes and statuses.",
          { language: "typescript" },
        ),
        mcq(
          "ts-3-b",
          "After `if (typeof x === \"string\")`, TypeScript treats `x` as…",
          ["string", "unknown", "any", "string | number"],
          "string",
          "That's control-flow narrowing. The compiler follows your checks.",
        ),
        fill(
          "ts-3-c",
          "A value that might be missing.",
          "let user: User | ___;",
          ["null", "any", "void", "never"],
          "null",
          "Union with `null` (or `undefined`) is the honest model for optional data.",
          { language: "typescript" },
        ),
        mcq(
          "ts-3-d",
          "What is `never` used for?",
          ["A state that should not happen", "An empty array", "Optional fields", "Async functions"],
          "A state that should not happen",
          "Exhaustive `switch`es often return `never` in the default branch.",
        ),
      ]),
      lesson("ts-4", "Generics", [
        fill(
          "ts-4-a",
          "Identity function that keeps the input type.",
          "function id<T>(value: T): ___ {",
          ["T", "any", "unknown", "value"],
          "T",
          "The generic `T` is captured from the argument and reused in the return type.",
          { language: "typescript" },
        ),
        mcq(
          "ts-4-b",
          "What is `Array<string>` the same as?",
          ["string[]", "string", "[string]", "Array"],
          "string[]",
          "Both notations mean “an array of strings”. `string[]` is more common.",
        ),
        output(
          "ts-4-c",
          "What type does `id(\"looply\")` infer for `T`?",
          "function id<T>(value: T): T {\n  return value;\n}",
          ['"looply" or string', "unknown", "any", "object"],
          '"looply" or string',
          "TypeScript infers `T` from the argument. A string literal may stay literal.",
          { language: "typescript" },
        ),
        typeIn(
          "ts-4-d",
          "The conventional first generic parameter name (one letter):",
          "T",
          "`T` stands for “type”. Next ones are often `K`, `V`, or `U`.",
        ),
      ]),
    ]),
  ],
};
