import type { Unit } from "@/lib/types";

export const gitUnit: Unit = {
  id: "git",
  title: "Git",
  subtitle: "History you can trust",
  language: "Git",
  accent: "#ff8a65",
  lessons: [
    {
      id: "basics",
      title: "Commits & staging",
      blurb: "Working tree, index, and HEAD.",
      xp: 20,
      exercises: [
        {
          id: "git-bas-1",
          type: "mcq",
          prompt: "`git add` copies changes into…",
          choices: ["HEAD", "the working tree", "the index (staging area)", "origin"],
          answer: 2,
          explanation: "The index is the next commit snapshot. `commit` records whatever is staged.",
        },
        {
          id: "git-bas-2",
          type: "order",
          prompt: "Save a staged snapshot.",
          tokens: ["git", "commit", "-m", "\"fix login\""],
          explanation: "`git commit -m` records the index with a message. Unstaged files stay out.",
        },
        {
          id: "git-bas-3",
          type: "blank",
          prompt: "Ignore local env files.",
          code: "echo .env >> ___",
          choices: [".ignore", ".gitignore", ".gitkeep", "EXCLUDE"],
          answer: ".gitignore",
          explanation: "Patterns in `.gitignore` skip untracked files. Tracked files need `git rm --cached`.",
        },
        {
          id: "git-bas-4",
          type: "mcq",
          prompt: "HEAD usually points to…",
          choices: [
            "The remote named origin",
            "The current branch tip (or a commit, if detached)",
            "The staging area",
            "The first commit",
          ],
          answer: 1,
          explanation: "On a branch, HEAD → branch → commit. Detached HEAD points at a commit directly.",
        },
        {
          id: "git-bas-5",
          type: "bug",
          prompt: "Which command rewrites the last commit and is risky if already pushed?",
          lines: [
            "git status",
            "git log --oneline",
            "git commit --amend",
            "git diff",
          ],
          answer: 2,
          explanation: "`--amend` replaces the last commit (new hash). Amending a published commit forces a rewrite.",
        },
        {
          id: "git-bas-6",
          type: "output",
          prompt: "clone vs fork — which is true?",
          choices: [
            "They are identical",
            "Clone copies a repo locally; fork copies it on the host under your account",
            "Fork only works offline",
            "Clone always creates a GitHub repo",
          ],
          answer: 1,
          explanation: "Fork is a server-side copy (your namespace). Clone is a local copy of any remote.",
        },
      ],
    },
    {
      id: "collaborate",
      title: "Branches & history",
      blurb: "merge, rebase, revert, reset.",
      xp: 24,
      exercises: [
        {
          id: "git-col-1",
          type: "mcq",
          prompt: "merge vs rebase — rebase…",
          choices: [
            "Creates a merge commit always",
            "Replays your commits on top of another tip (rewrites hashes)",
            "Deletes the remote branch",
            "Cannot cause conflicts",
          ],
          answer: 1,
          explanation: "Rebase moves commits, changing their hashes. Merge joins histories with a merge commit (usually).",
        },
        {
          id: "git-col-2",
          type: "blank",
          prompt: "Undo a commit that is already on main, without rewriting history.",
          code: "git ___ <sha>",
          choices: ["reset", "revert", "rebase", "restore"],
          answer: "revert",
          explanation: "`git revert` adds a new commit that inverts a previous one. Safe for shared branches.",
        },
        {
          id: "git-col-3",
          type: "order",
          prompt: "Park local changes and switch.",
          tokens: ["git", "stash", "push", "-m", "wip"],
          explanation: "`git stash` shelves uncommitted work so you can change branches cleanly.",
        },
        {
          id: "git-col-4",
          type: "mcq",
          prompt: "Fast-forward merge happens when…",
          choices: [
            "Histories have diverged",
            "The target branch has no extra commits; it can just slide to the other tip",
            "You always force --no-ff",
            "There are conflicts",
          ],
          answer: 1,
          explanation: "If main has not moved, merging a feature branch can simply move the pointer forward.",
        },
        {
          id: "git-col-5",
          type: "bug",
          prompt: "Dangerous on a shared branch — which one?",
          lines: [
            "git pull --rebase",
            "git revert HEAD",
            "git reset --hard origin/main",
            "git status",
          ],
          answer: 2,
          explanation: "`reset --hard` drops local commits and uncommitted work. On a shared branch it rewrites what teammates have.",
        },
        {
          id: "git-col-6",
          type: "mcq",
          prompt: "Detached HEAD means…",
          choices: [
            "The repo is corrupted",
            "HEAD points at a commit, not a branch name",
            "You have no remotes",
            "Staging is empty",
          ],
          answer: 1,
          explanation: "Checking out a SHA or tag detaches HEAD. New commits can be lost unless you create a branch.",
        },
      ],
    },
  ],
};
