import type { Unit } from "@/lib/types";

export const javascriptUnit: Unit = {
  id: "javascript",
  title: "JavaScript",
  subtitle: "The language of the web",
  language: "JS",
  accent: "#ffc14a",
  lessons: [
    {
      id: "values",
      title: "Values & equality",
      blurb: "let, const, and the equality traps that show up in reviews.",
      xp: 20,
      exercises: [
        {
          id: "js-values-1",
          type: "mcq",
          prompt: "Which declaration can be reassigned but not redeclared in the same scope?",
          choices: ["var", "let", "const", "function"],
          answer: 1,
          explanation: "`let` is block-scoped and can be reassigned. `const` cannot. `var` can do both and also redeclare.",
        },
        {
          id: "js-values-2",
          type: "output",
          prompt: "What does this log?",
          code: "console.log(typeof null)",
          choices: ['"null"', '"object"', '"undefined"', '"boolean"'],
          answer: 1,
          explanation: "A historic bug: `typeof null` is `\"object\"`. Check with `value === null` instead.",
        },
        {
          id: "js-values-3",
          type: "mcq",
          prompt: "Which comparison is true?",
          choices: ["0 === \"0\"", "0 == \"0\"", "NaN === NaN", "null === undefined"],
          answer: 1,
          explanation: "`==` coerces, so `0 == \"0\"`. `===` does not. `NaN` is never equal to itself; use `Number.isNaN`.",
        },
        {
          id: "js-values-4",
          type: "order",
          prompt: "Build a constant greeting.",
          tokens: ["const", "hi", "=", "`hey ${name}`"],
          explanation: "Template literals use backticks. `const hi = \\`hey ${name}\\`` interpolates `name`.",
        },
        {
          id: "js-values-5",
          type: "blank",
          prompt: "Fill the missing method so this is a number.",
          code: "const n = Number.___('42')",
          choices: ["parseInt", "parseFloat", "isNaN", "toString"],
          answer: "parseInt",
          explanation: "`Number.parseInt('42')` (or `Number.parseFloat`) turns a numeric string into a number. Prefer these over globals.",
        },
        {
          id: "js-values-6",
          type: "bug",
          prompt: "Which line throws?",
          lines: [
            "const user = { name: 'Ali' }",
            "user.name = 'Slaimia'",
            "user = { name: 'Pip' }",
            "console.log(user.name)",
          ],
          answer: 2,
          explanation: "`const` blocks reassignment of the binding, not mutation of the object. Line 3 reassigns `user`.",
        },
      ],
    },
    {
      id: "arrays",
      title: "Arrays & objects",
      blurb: "map, filter, and the destructuring you actually use.",
      xp: 22,
      exercises: [
        {
          id: "js-arr-1",
          type: "output",
          prompt: "What is printed?",
          code: "console.log([1, 2, 3].map((n) => n * 2))",
          choices: ["[1, 2, 3]", "[2, 4, 6]", "6", "[1, 4, 9]"],
          answer: 1,
          explanation: "`map` returns a new array of the same length with each item transformed.",
        },
        {
          id: "js-arr-2",
          type: "mcq",
          prompt: "You need only the even numbers. Which method?",
          choices: ["map", "forEach", "filter", "reduce"],
          answer: 2,
          explanation: "`filter` keeps items that pass a predicate. `map` always returns the same length.",
        },
        {
          id: "js-arr-3",
          type: "order",
          prompt: "Destructure `name` from `user`.",
          tokens: ["const", "{", "name", "}", "=", "user"],
          explanation: "`const { name } = user` pulls `user.name` into a variable.",
        },
        {
          id: "js-arr-4",
          type: "blank",
          prompt: "Safe-read a nested field.",
          code: "const city = user___address?.city",
          choices: ["?.", "??", "&&", "||"],
          answer: "?.",
          explanation: "Optional chaining `?.` stops the chain if `user` or `address` is nullish, returning `undefined`.",
        },
        {
          id: "js-arr-5",
          type: "bug",
          prompt: "This should list names, not mutate the source. Which line is wrong?",
          lines: [
            "const names = []",
            "users.map((u) => {",
            "  names.push(u.name)",
            "})",
          ],
          answer: 2,
          explanation: "`map` is for transforming. Pushing into an outer array is a side effect — use `forEach` or `users.map(u => u.name)`.",
        },
        {
          id: "js-arr-6",
          type: "mcq",
          prompt: "What does `??` do in `port ?? 3000`?",
          choices: [
            "Uses 3000 if port is 0",
            "Uses 3000 if port is null or undefined",
            "Uses 3000 if port is false",
            "Always uses 3000",
          ],
          answer: 1,
          explanation: "Nullish coalescing only falls back for `null`/`undefined`. `0` and `''` stay.",
        },
      ],
    },
    {
      id: "async",
      title: "Async & fetch",
      blurb: "Promises, await, and errors that escape.",
      xp: 24,
      exercises: [
        {
          id: "js-async-1",
          type: "mcq",
          prompt: "A Promise is not in which state?",
          choices: ["pending", "fulfilled", "rejected", "cancelled"],
          answer: 3,
          explanation: "Promises have pending, fulfilled, or rejected. Cancellation is not a built-in state.",
        },
        {
          id: "js-async-2",
          type: "order",
          prompt: "Read JSON from a successful fetch.",
          tokens: ["const", "data", "=", "await", "res.json()"],
          explanation: "`res.json()` returns a Promise, so it needs `await` (inside an async function).",
        },
        {
          id: "js-async-3",
          type: "bug",
          prompt: "Which line is the bug?",
          lines: [
            "async function loadUser(id) {",
            "  const res = fetch('/api/users/' + id)",
            "  if (!res.ok) throw new Error('fail')",
            "  return res.json()",
            "}",
          ],
          answer: 1,
          explanation: "`fetch` is async. Without `await`, `res` is a Promise, so `res.ok` is wrong and you skip waiting.",
        },
        {
          id: "js-async-4",
          type: "output",
          prompt: "What order is logged?",
          code: "console.log('A')\nPromise.resolve().then(() => console.log('B'))\nconsole.log('C')",
          choices: ["A B C", "A C B", "B A C", "C B A"],
          answer: 1,
          explanation: "The `.then` callback is a microtask. It runs after the current call stack — so A, C, then B.",
        },
        {
          id: "js-async-5",
          type: "blank",
          prompt: "Wait for every job, fail if any rejects.",
          code: "const rows = await Promise.___(jobs)",
          choices: ["all", "race", "any", "allSettled"],
          answer: "all",
          explanation: "`Promise.all` fulfills with every result, or rejects on the first failure. `allSettled` never rejects.",
        },
        {
          id: "js-async-6",
          type: "mcq",
          prompt: "Why still check `res.ok` after fetch?",
          choices: [
            "fetch throws on 404",
            "fetch only throws on network failure, not HTTP error codes",
            "json() throws on 500",
            "await handles status codes",
          ],
          answer: 1,
          explanation: "`fetch` rejects on network errors, not on 404/500. You must read `res.ok` or `res.status`.",
        },
      ],
    },
  ],
};
