import type { Unit } from "@/lib/types";

export const pythonUnit: Unit = {
  id: "python",
  title: "Python",
  subtitle: "Clear syntax, sharp edges",
  language: "PY",
  accent: "#7ec8ff",
  lessons: [
    {
      id: "syntax",
      title: "Syntax & types",
      blurb: "f-strings, truthiness, and is vs ==.",
      xp: 20,
      exercises: [
        {
          id: "py-syn-1",
          type: "order",
          prompt: "Interpolate a name with an f-string.",
          tokens: ["msg", "=", "f'hi {name}'"],
          explanation: "f-strings evaluate expressions inside `{...}`.",
        },
        {
          id: "py-syn-2",
          type: "mcq",
          prompt: "Which is a tuple?",
          choices: ["[1, 2]", "{1, 2}", "(1, 2)", "{'a': 1}"],
          answer: 2,
          explanation: "Tuples use parentheses and are immutable. Lists `[]`, sets `{}` with values, dicts with keys.",
        },
        {
          id: "py-syn-3",
          type: "output",
          prompt: "What prints?",
          code: "print(bool([]) , bool('0'), bool(None))",
          choices: ["False False False", "False True False", "True True False", "False True True"],
          answer: 1,
          explanation: "Empty containers are falsy. Non-empty strings (even `'0'`) are truthy. `None` is falsy.",
        },
        {
          id: "py-syn-4",
          type: "blank",
          prompt: "Identity check, not equality.",
          code: "if value ___ None:",
          choices: ["==", "is", "=", "!="],
          answer: "is",
          explanation: "PEP 8: use `is`/`is not` for `None`. `==` can be overloaded by `__eq__`.",
        },
        {
          id: "py-syn-5",
          type: "bug",
          prompt: "Which comparison is the footgun?",
          lines: [
            "a = [1, 2]",
            "b = [1, 2]",
            "print(a == b)",
            "print(a is b)",
          ],
          answer: 3,
          explanation: "`==` is True (same contents). `is` is False (different objects). Don't use `is` for value equality.",
        },
        {
          id: "py-syn-6",
          type: "mcq",
          prompt: "What does `//` do?",
          choices: ["Comment", "Float divide", "Floor divide", "Power"],
          answer: 2,
          explanation: "`//` is floor division (`7 // 2 == 3`). `#` comments, `/` true divide, `**` power.",
        },
      ],
    },
    {
      id: "collections",
      title: "Lists & dicts",
      blurb: "Comprehensions, slices, and get().",
      xp: 22,
      exercises: [
        {
          id: "py-col-1",
          type: "output",
          prompt: "What is `nums[-1]`?",
          code: "nums = [10, 20, 30]\nprint(nums[-1])",
          choices: ["10", "20", "30", "Error"],
          answer: 2,
          explanation: "Negative indices count from the end. `-1` is the last item.",
        },
        {
          id: "py-col-2",
          type: "order",
          prompt: "Squares of 0..2 with a comprehension.",
          tokens: ["squares", "=", "[", "x**2", "for", "x", "in", "range(3)", "]"],
          explanation: "`[x**2 for x in range(3)]` yields `[0, 1, 4]`.",
        },
        {
          id: "py-col-3",
          type: "blank",
          prompt: "Read a key without KeyError.",
          code: "city = user.___('city', 'Bizerte')",
          choices: ["get", "pop", "setdefault", "keys"],
          answer: "get",
          explanation: "`dict.get(key, default)` returns the default instead of raising if the key is missing.",
        },
        {
          id: "py-col-4",
          type: "mcq",
          prompt: "What does `{1, 2, 2, 3}` become?",
          choices: ["[1, 2, 2, 3]", "{1, 2, 3}", "{1, 2, 2, 3}", "Error"],
          answer: 1,
          explanation: "Sets store unique values, so the duplicate `2` disappears.",
        },
        {
          id: "py-col-5",
          type: "output",
          prompt: "Slice result?",
          code: "print('bytetrail'[0:4])",
          choices: ["byte", "bytetr", "byte trail", "ytes"],
          answer: 0,
          explanation: "Slices are [start, end) — index 4 is not included, so `'byte'`.",
        },
        {
          id: "py-col-6",
          type: "bug",
          prompt: "Unpacking should grab first and rest. Which line is wrong?",
          lines: [
            "head, *tail = [1, 2, 3]",
            "print(head)",
            "print(tail)",
            "head, tail = [1, 2, 3]",
          ],
          answer: 3,
          explanation: "Without `*`, the left side must match length. `[1, 2, 3]` cannot unpack into two names.",
        },
      ],
    },
    {
      id: "flow",
      title: "Flow & pitfalls",
      blurb: "enumerate, files, and the mutable default trap.",
      xp: 24,
      exercises: [
        {
          id: "py-flow-1",
          type: "order",
          prompt: "Loop with index and value.",
          tokens: ["for", "i,", "item", "in", "enumerate(rows):"],
          explanation: "`enumerate(rows)` yields `(index, item)` pairs. Default start is 0.",
        },
        {
          id: "py-flow-2",
          type: "mcq",
          prompt: "Best way to open a file?",
          choices: [
            "f = open(path); f.read()",
            "with open(path) as f: f.read()",
            "os.read(path)",
            "Path.read() without a path",
          ],
          answer: 1,
          explanation: "`with` closes the file even if an exception is thrown.",
        },
        {
          id: "py-flow-3",
          type: "bug",
          prompt: "Classic interview trap — which line is the bug?",
          lines: [
            "def append(item, bucket=[]):",
            "    bucket.append(item)",
            "    return bucket",
            "# later calls share the same list",
          ],
          answer: 0,
          explanation: "Default `[]` is created once. Later calls reuse it. Use `bucket=None` and assign `bucket = []` inside.",
        },
        {
          id: "py-flow-4",
          type: "blank",
          prompt: "Inclusive range-like loop over 1..3.",
          code: "for n in range(1, ___):",
          choices: ["3", "4", "2", "1"],
          answer: "4",
          explanation: "`range` is exclusive on the end: `range(1, 4)` → 1, 2, 3.",
        },
        {
          id: "py-flow-5",
          type: "output",
          prompt: "What prints?",
          code: "x = 0\nfor x in range(3):\n    pass\nprint(x)",
          choices: ["0", "2", "3", "NameError"],
          answer: 1,
          explanation: "The loop variable leaks. After `range(3)` it is `2`.",
        },
        {
          id: "py-flow-6",
          type: "mcq",
          prompt: "`except Exception` does not catch which?",
          choices: ["ValueError", "KeyError", "KeyboardInterrupt", "RuntimeError"],
          answer: 2,
          explanation: "`KeyboardInterrupt` and `SystemExit` inherit from `BaseException`, not `Exception`.",
        },
      ],
    },
  ],
};
