import type { Unit } from "@/lib/types";

export const reactUnit: Unit = {
  id: "react",
  title: "React",
  subtitle: "UI as a function of state",
  language: "RX",
  accent: "#5ad1e6",
  lessons: [
    {
      id: "components",
      title: "Components & props",
      blurb: "Keys, lifting state, and composition.",
      xp: 22,
      exercises: [
        {
          id: "rx-cp-1",
          type: "mcq",
          prompt: "Props are…",
          choices: ["Mutable from the child", "Read-only inputs from the parent", "Always strings", "Stored in localStorage"],
          answer: 1,
          explanation: "A child should not mutate props. To change them, lift state up and pass a setter.",
        },
        {
          id: "rx-cp-2",
          type: "blank",
          prompt: "List items need a stable identity.",
          code: "users.map((u) => <Row ___={u.id} user={u} />)",
          choices: ["id", "key", "ref", "index"],
          answer: "key",
          explanation: "`key` helps React match items across renders. Prefer IDs over array indexes if the list can reorder.",
        },
        {
          id: "rx-cp-3",
          type: "order",
          prompt: "Lift the count into parent state.",
          tokens: ["const", "[count,", "setCount]", "=", "useState(0)"],
          explanation: "`useState` holds values that should survive renders and trigger UI updates.",
        },
        {
          id: "rx-cp-4",
          type: "bug",
          prompt: "Which key usage is the smell?",
          lines: [
            "items.map((item) => (",
            "  <Card key={Math.random()} item={item} />",
            "))",
            "// keys should be stable",
          ],
          answer: 1,
          explanation: "Random keys remount every render and reset state. Use a stable id from data.",
        },
        {
          id: "rx-cp-5",
          type: "mcq",
          prompt: "Prefer composition over…",
          choices: ["hooks", "inheritance for UI variants", "props", "children"],
          answer: 1,
          explanation: "React favors wrapping components (`children`, slots) instead of class inheritance trees.",
        },
        {
          id: "rx-cp-6",
          type: "output",
          prompt: "What does `{count && <Badge />}` render when count is 0?",
          choices: ["<Badge />", "nothing (false)", "0", "an error"],
          answer: 2,
          explanation: "`0` is falsy so the Badge is skipped, but React still renders `0`. Use `count > 0 && ...`.",
        },
      ],
    },
    {
      id: "hooks",
      title: "State & effects",
      blurb: "Rules of Hooks, deps, derived state.",
      xp: 24,
      exercises: [
        {
          id: "rx-hk-1",
          type: "mcq",
          prompt: "Hooks must not be called…",
          choices: [
            "In nested functions or conditions",
            "At the top of a function component",
            "Inside a custom hook",
            "On every render",
          ],
          answer: 0,
          explanation: "Same order every render: top level of components/custom hooks, not inside if/loops.",
        },
        {
          id: "rx-hk-2",
          type: "blank",
          prompt: "Run after paint when `id` changes.",
          code: "useEffect(() => { load(id) }, [___])",
          choices: ["id", "{}", "load", "undefined"],
          answer: "id",
          explanation: "Put reactive values used inside the effect in the dependency array. `[]` would stale-close `id`.",
        },
        {
          id: "rx-hk-3",
          type: "bug",
          prompt: "Stale closure — which line is the bug?",
          lines: [
            "function Tick() {",
            "  const [n, setN] = useState(0)",
            "  useEffect(() => {",
            "    const id = setInterval(() => setN(n + 1), 1000)",
            "    return () => clearInterval(id)",
            "  }, [])",
          ],
          answer: 3,
          explanation: "`n` is captured as 0. Use `setN(v => v + 1)` or include `n` in deps (and clear the interval).",
        },
        {
          id: "rx-hk-4",
          type: "mcq",
          prompt: "You can derive `fullName` from `first` + `last`. Should you store it in state?",
          choices: [
            "Yes, always",
            "No — compute it during render",
            "Yes, inside useEffect",
            "Only with useMemo always",
          ],
          answer: 1,
          explanation: "Derived values should be calculated in render. Extra state gets out of sync. `useMemo` is optional.",
        },
        {
          id: "rx-hk-5",
          type: "order",
          prompt: "A tiny custom hook.",
          tokens: ["function", "useToggle(start)", "{", "const", "[on,", "setOn]", "=", "useState(start)"],
          explanation: "Custom hooks are functions named `use*` that call other hooks. They share stateful logic, not UI.",
        },
        {
          id: "rx-hk-6",
          type: "mcq",
          prompt: "`useMemo` is worth it when…",
          choices: [
            "Every variable you declare",
            "The calculation is expensive and deps change rarely",
            "You want to skip writing deps",
            "It replaces useState",
          ],
          answer: 1,
          explanation: "Memoization has a cost. Use it for real work (big lists, heavy charts), not by default.",
        },
      ],
    },
  ],
};
