import type { Unit } from "@/lib/types";

export const sqlUnit: Unit = {
  id: "sql",
  title: "SQL",
  subtitle: "Ask the database the right question",
  language: "SQL",
  accent: "#c4a5ff",
  lessons: [
    {
      id: "select",
      title: "SELECT & WHERE",
      blurb: "Filters, NULL, and LIMIT.",
      xp: 22,
      exercises: [
        {
          id: "sql-sel-1",
          type: "order",
          prompt: "Names of active users.",
          tokens: ["SELECT", "name", "FROM", "users", "WHERE", "active", "=", "TRUE"],
          explanation: "SELECT columns, FROM table, WHERE filter. Boolean columns can be compared to TRUE.",
        },
        {
          id: "sql-sel-2",
          type: "mcq",
          prompt: "`WHERE country = NULL` returns…",
          choices: ["Rows where country is NULL", "No rows", "Every row", "A syntax error always"],
          answer: 1,
          explanation: "Nothing equals NULL, including NULL. Use `IS NULL` / `IS NOT NULL`.",
        },
        {
          id: "sql-sel-3",
          type: "blank",
          prompt: "Keep unique cities.",
          code: "SELECT ___ city FROM offices",
          choices: ["UNIQUE", "DISTINCT", "ONLY", "DIFFERENT"],
          answer: "DISTINCT",
          explanation: "`DISTINCT` deduplicates the result set. `UNIQUE` is a constraint, not a SELECT clause.",
        },
        {
          id: "sql-sel-4",
          type: "output",
          prompt: "What does `LIMIT 2 OFFSET 2` return from (a,b,c,d)?",
          choices: ["a, b", "b, c", "c, d", "a, b, c, d"],
          answer: 2,
          explanation: "OFFSET skips 2 (`a`,`b`), LIMIT takes the next 2 (`c`,`d`). Order must be defined for this to be stable.",
        },
        {
          id: "sql-sel-5",
          type: "mcq",
          prompt: "`WHERE name LIKE 'A%'` matches…",
          choices: ["Names ending with A", "Names containing A", "Names starting with A", "Exact 'A%'"],
          answer: 2,
          explanation: "`%` is a wildcard for any suffix. `A%` means starts with A.",
        },
        {
          id: "sql-sel-6",
          type: "bug",
          prompt: "Which line will not filter salaries as intended?",
          lines: [
            "SELECT name, salary",
            "FROM employees",
            "WHERE salary BETWEEN 50 AND 80",
            "WHERE salary = NULL",
          ],
          answer: 3,
          explanation: "`= NULL` is never true. Also you cannot have two WHERE clauses — combine with AND.",
        },
      ],
    },
    {
      id: "joins",
      title: "JOINs & aggregates",
      blurb: "INNER vs LEFT, GROUP BY, HAVING.",
      xp: 24,
      exercises: [
        {
          id: "sql-join-1",
          type: "mcq",
          prompt: "LEFT JOIN users → orders keeps…",
          choices: [
            "Only users who have orders",
            "All users; missing orders become NULL",
            "All orders; missing users become NULL",
            "The Cartesian product only",
          ],
          answer: 1,
          explanation: "LEFT JOIN keeps every row from the left table. Non-matches pad the right side with NULL.",
        },
        {
          id: "sql-join-2",
          type: "order",
          prompt: "Count orders per user.",
          tokens: ["SELECT", "user_id,", "COUNT(*)", "FROM", "orders", "GROUP", "BY", "user_id"],
          explanation: "Non-aggregated columns in SELECT must appear in GROUP BY.",
        },
        {
          id: "sql-join-3",
          type: "blank",
          prompt: "Filter groups, not rows.",
          code: "SELECT user_id, COUNT(*) FROM orders GROUP BY user_id ___ COUNT(*) > 3",
          choices: ["WHERE", "HAVING", "AND", "LIMIT"],
          answer: "HAVING",
          explanation: "`WHERE` filters rows before grouping. `HAVING` filters after aggregates.",
        },
        {
          id: "sql-join-4",
          type: "mcq",
          prompt: "INNER JOIN vs LEFT JOIN — when are they equal?",
          choices: [
            "Always",
            "When every left row has a match",
            "When there are NULLs",
            "Never",
          ],
          answer: 1,
          explanation: "If the join key always matches, INNER and LEFT return the same set (plus column order/select list).",
        },
        {
          id: "sql-join-5",
          type: "bug",
          prompt: "Which SELECT is invalid with GROUP BY?",
          lines: [
            "SELECT user_id, COUNT(*)",
            "FROM orders",
            "GROUP BY user_id",
            "SELECT user_id, email, COUNT(*) FROM orders GROUP BY user_id",
          ],
          answer: 3,
          explanation: "`email` is neither aggregated nor in GROUP BY (in strict SQL). Postgres/MySQL ONLY_FULL_GROUP_BY reject it.",
        },
        {
          id: "sql-join-6",
          type: "output",
          prompt: "`COUNT(*)` vs `COUNT(email)` if 3 rows and 1 NULL email?",
          choices: ["3 and 3", "3 and 2", "2 and 3", "0 and 3"],
          answer: 1,
          explanation: "`COUNT(*)` counts rows. `COUNT(col)` skips NULLs.",
        },
      ],
    },
  ],
};
