import type { Unit } from "@/lib/types";

export const typescriptUnit: Unit = {
  id: "typescript",
  title: "TypeScript",
  subtitle: "Types that survive code review",
  language: "TS",
  accent: "#7cffb2",
  lessons: [
    {
      id: "types",
      title: "Types & narrowing",
      blurb: "unknown, unions, and optional fields.",
      xp: 22,
      exercises: [
        {
          id: "ts-ty-1",
          type: "mcq",
          prompt: "Which is safer for untrusted input?",
          choices: ["any", "unknown", "object", "never"],
          answer: 1,
          explanation: "`unknown` forces you to narrow before use. `any` turns the type checker off.",
        },
        {
          id: "ts-ty-2",
          type: "blank",
          prompt: "Mark `nickname` as optional.",
          code: "type User = { name: string; nickname___ string }",
          choices: ["?:", "!:", "|", "?:?"],
          answer: "?:",
          explanation: "`nickname?: string` means the property may be missing or `undefined`.",
        },
        {
          id: "ts-ty-3",
          type: "order",
          prompt: "Narrow a union with `typeof`.",
          tokens: ["if", "(typeof", "value", "===", "'string')"],
          explanation: "After `typeof value === 'string'`, TypeScript treats `value` as `string` in that block.",
        },
        {
          id: "ts-ty-4",
          type: "bug",
          prompt: "Which line is a type error with `strict` on?",
          lines: [
            "function len(text: string) {",
            "  return text.length",
            "}",
            "len(null)",
          ],
          answer: 3,
          explanation: "`null` is not a `string` under `strictNullChecks`. Handle `string | null` explicitly.",
        },
        {
          id: "ts-ty-5",
          type: "mcq",
          prompt: "`interface` vs `type` — which is true?",
          choices: [
            "Only type can declare object shapes",
            "Interfaces can be merged; type aliases cannot",
            "Types do not support unions",
            "Interfaces support unions with `|`",
          ],
          answer: 1,
          explanation: "Declaration merging works for interfaces. Use `type` for unions, tuples, and mapped types.",
        },
        {
          id: "ts-ty-6",
          type: "output",
          prompt: "What is the type of `x` after this?",
          code: "const x = [1, 2, 3] as const",
          choices: ["number[]", "readonly [1, 2, 3]", "[number, number, number]", "Array<1 | 2 | 3>"],
          answer: 1,
          explanation: "`as const` infers a readonly tuple of literal types `[1, 2, 3]`.",
        },
      ],
    },
    {
      id: "applied",
      title: "Generics & utility types",
      blurb: "Pick, Omit, and discriminated unions.",
      xp: 24,
      exercises: [
        {
          id: "ts-ap-1",
          type: "blank",
          prompt: "A list of one type of item.",
          code: "function first<___>(items: T[]): T | undefined { return items[0] }",
          choices: ["T", "any", "unknown", "never"],
          answer: "T",
          explanation: "The generic `T` is already in the signature — this is the pattern: input `T[]`, output `T`.",
        },
        {
          id: "ts-ap-2",
          type: "mcq",
          prompt: "`Pick<User, 'id' | 'name'>` creates…",
          choices: [
            "User minus those keys",
            "A type with only id and name from User",
            "A runtime object",
            "A Partial User",
          ],
          answer: 1,
          explanation: "`Pick` keeps listed keys. `Omit` removes them. These are compile-time only.",
        },
        {
          id: "ts-ap-3",
          type: "order",
          prompt: "A discriminated union variant.",
          tokens: ["type", "Ok", "=", "{", "ok:", "true;", "data:", "User", "}"],
          explanation: "A boolean (or string) tag like `ok: true` lets `if (result.ok)` narrow the rest of the fields.",
        },
        {
          id: "ts-ap-4",
          type: "bug",
          prompt: "Which line breaks exhaustiveness?",
          lines: [
            "type Status = 'open' | 'closed'",
            "function label(s: Status) {",
            "  if (s === 'open') return 'Open'",
            "  return s satisfies never",
            "}",
          ],
          answer: 3,
          explanation: "`closed` is still possible, so `s` is not `never`. Handle every variant or the `satisfies never` check fails.",
        },
        {
          id: "ts-ap-5",
          type: "mcq",
          prompt: "What is `Record<string, number>`?",
          choices: [
            "A Map instance",
            "An object type with string keys and number values",
            "An array of numbers",
            "A tuple",
          ],
          answer: 1,
          explanation: "`Record<K, V>` is `{ [key in K]: V }`. It is a type, not the `Map` class.",
        },
        {
          id: "ts-ap-6",
          type: "blank",
          prompt: "Drop `password` from `User`.",
          code: "type PublicUser = ___<User, 'password'>",
          choices: ["Pick", "Omit", "Exclude", "Partial"],
          answer: "Omit",
          explanation: "`Omit<User, 'password'>` copies User without that key. `Exclude` works on unions, not object keys.",
        },
      ],
    },
  ],
};
